language: php
php:
    - 7.3

install:
    - composer install

cache:
    directories:
        - ./vendor

script:
    - vendor/bin/phpunit -c application/tests/

after_success:
  - travis_retry php vendor/bin/php-coveralls
