language: php
php:
    - 7.3

install:
    - mkdir -p build/logs
    - composer install

cache:
    directories:
        - ./vendor

script:
    - vendor/bin/phpunit -c application/tests/

after_success:
  - travis_retry vendor/bin/php-coveralls -v --exclude-no-stmt
